### ISSUE TITLE
Linux - Inconsistent MIDI behavior

### ISSUE THREAD

**Issue by crshrprt** [ardura/Actuate#22]
I was testing Actuate on different hosts and I noticed that Actuate behave inconsistently on MIDI note input:

Bespoke Synth
- Actuate responds to midi notes from MIDI external devices/ports. 
- Actuate doesn't respond when MIDI is generated/played inside Bespoke Synth itself.

Ardour
- Actuate doesn't respond to midi notes from MIDI external devices/ports. 
- Actuate responds to MIDI when playing MIDI clips but: 
1. Only a long sustained (stuck?) note is played
2. Only the first note of the MIDI clip is played, the other notes of the MIDI clip are ignored.

Carla 
- Actuate doesn't respond to midi notes regardless of their origin (external devices/ports, other plugins, etc.)

**Comment by ardura** [comment]
Hey crshrprt, sorry about that! Can you see if you can build and run this "poly_mod_synth" from nih_plug? I want to see if the same behavior happens on another synth using the same library or if this is limited to something I messed up in Actuate's MIDI processing somewhere.

https://github.com/robbert-vdh/nih-plug/tree/master/plugins/examples/poly_mod_synth

For the long sustained note being played, I know that happens when the plugin never receives a note off event(or maybe one it can recognize).

**Comment by crshrprt** [comment]
poly_mod_synth works fine in all hosts, all the MIDI notes are correctly played in Bespoke Synth, Ardour and Carla.

**Comment by ardura** [comment]
Hey again, that means I messed something up with midi processing oops. I'll take a look at this in the coming days sorry about that, moving between homes right now. 

Does the behavior still persist if you put the max voices to 1 in the top bar of Actuate? (Not the voices of an osc)

Since Actuate is built off the poly mod synth code, I'm wondering if the changes I made to voice handling are the source of this. Since I think poly mod synth is only 1 voice. Thanks again for finding these bugs and reporting them so nicely :)

**Comment by crshrprt** [comment]
Reducing the voices is something I had already tried, however I tested it again.
Something new I noticed is that if I let some MIDI notes playing for a minute or so eventually Actuate will start to play at random, but is always single "stuck note".

**Comment by ardura** [comment]
So I looked through polymod synth some and it has changed some since I started developing Actuate. I still haven't found the cause of the behavior you're seeing but I took a guess at some changes to remove a few checks that might prevent MIDI from being stopped or ignored. Can you try with this branch?

If it still doesn't work, I may look at if upgrading some of the dependencies would help since I don't see much other things it could be unfortunately.

https://github.com/ardura/Actuate/tree/MIDI-changes

**Comment by ardura** [comment]
I started working on upgrading dependencies anyways so hopefully some of the MIDI handling and usage gets better in addition to some improvements/stability. I should have that done in the next few days if the MIDI-changes branch doesn't fix/change some of the issues you're seeing.

**Comment by crshrprt** [comment]
@ardura Yes, it seems that MIDI-changes branch works in all the hosts I tried! :)

**Comment by ardura** [comment]
Merged into Main in https://github.com/ardura/Actuate/commit/52fb152c3d0ad656251db6906c5e4d04d6271a2d so now you don't have to use MIDI-changes branch
